// Operates every control on every Settings page and in the Control Center, and checks its visible effect.
const { chromium } = require(process.env.PLAYWRIGHT || 'playwright');
const fs = require('fs'), zlib = require('zlib');
// tiny PNG served by the dev server for the custom-background test (removed at the end)
const BG = require('path').join(__dirname, '../../web/dev/__audit_bg.png');
(function png(w, h) {
  const crcT = []; for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; crcT[n] = c >>> 0; }
  const crc = (b) => { let c = 0xffffffff; for (const x of b) c = crcT[(c ^ x) & 255] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; };
  const chunk = (t, d) => { const len = Buffer.alloc(4); len.writeUInt32BE(d.length); const td = Buffer.concat([Buffer.from(t), d]); const c = Buffer.alloc(4); c.writeUInt32BE(crc(td)); return Buffer.concat([len, td, c]); };
  const ihdr = Buffer.alloc(13); ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 2;
  const raw = Buffer.alloc((w * 3 + 1) * h); for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) raw.set([200, 40, 120], y * (w * 3 + 1) + 1 + x * 3);
  fs.writeFileSync(BG, Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]));
})(32, 20);
process.on('exit', () => { try { fs.unlinkSync(BG); } catch {} });
(async () => {
  const b = await chromium.launch();
  const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
  const errors = [];
  p.on('pageerror', e => errors.push('pageerror: ' + e.message));
  p.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await p.goto((process.env.PDR_URL || 'http://localhost:8765/dev/'));
  const os = () => p.frames().find(f => f.url().includes('/os/index.html'));
  const send = (m) => p.evaluate(m => document.getElementById('os').contentWindow.postMessage(m, '*'), m);
  const S = () => os().evaluate(() => JSON.parse(localStorage.getItem('pdr_tablet:settings') || '{}'));
  const css = (sel, prop) => os().$eval(sel, (e, prop) => getComputedStyle(e)[prop], prop);
  const rootVar = (v) => os().evaluate(v => getComputedStyle(document.documentElement).getPropertyValue(v).trim(), v);
  const has = (sel) => os().$(sel).then(Boolean);
  const text = (sel) => os().$eval(sel, e => e.textContent);
  const wait = (ms = 250) => p.waitForTimeout(ms);
  const setRange = (sel, v) => os().$eval(sel, (e, v) => { e.value = v; e.dispatchEvent(new Event('input', { bubbles: true })); }, v);
  const page = async (name) => { await os().click(`.sidebar-row:has(span:text-is("${name}"))`); await wait(); };
  const rowCtl = (title, ctl) => `.row:has(.row-title:text-is("${title}")) ${ctl}`;
  let failed = 0;
  const check = (name, ok) => { if (!ok) failed++; console.log((ok ? 'PASS ' : 'FAIL ') + name); };

  await p.waitForTimeout(300);
  await os().evaluate(() => localStorage.clear());
  await p.reload(); await p.waitForTimeout(3600);
  await send({ action: 'os:unlock' }); await wait(500);
  for (const id of ['dev.a', 'dev.b']) await send({ action: 'apps:register', app: { id, label: id === 'dev.a' ? 'Alpha' : 'Bravo', url: 'http://localhost:8765/dev/sample-app/index.html' } });
  await send({ action: 'apps:launch', id: 'system.settings' }); await wait(600);

  console.log('— Appearance');
  await os().click('.style-choice:has-text("Default")'); await wait();
  check('style Default → light theme', (await os().evaluate(() => document.documentElement.dataset.theme)) === 'light' && (await S()).theme === 'light');
  await os().click('.style-choice:has-text("Dark")'); await wait();
  check('style Dark → dark theme', (await os().evaluate(() => document.documentElement.dataset.theme)) === 'dark');
  const accents = await os().$$eval('.accent-row .accent', els => els.map(e => e.title));
  let accentOk = true;
  for (const a of accents) {
    await os().click(`.accent-row .accent[title="${a}"]`); await wait(80);
    const color = (await S()).accent;
    const active = await os().$eval('.accent-row .accent.is-active', e => e.title);
    if (active !== a || (await rootVar('--accent')) !== color) accentOk = false;
  }
  check(`all ${accents.length} accent colors apply`, accentOk);
  const wps = await os().$$eval('.wp-grid .wp-item', els => els.map(e => e.title));
  const seen = new Set(); let wpOk = true;
  for (const w of wps) {
    await os().click(`.wp-grid .wp-item[title="${w}"]`); await wait(80);
    const bg = await os().$eval('#wallpaper', e => e.style.background);
    if (seen.has(bg) || !(await has(`.wp-item.is-active[title="${w}"]`))) wpOk = false;
    seen.add(bg);
  }
  check(`all ${wps.length} backgrounds apply and differ`, wpOk);
  await os().fill('.entry', 'not a url'); await os().click('.entry-row .btn'); await wait();
  check('custom bg: invalid URL rejected', (await text('.row-status')).includes('http'));
  await os().fill('.entry', 'http://localhost:8765/os/fonts/cantarell-latin-400-normal.woff2'); await os().click('.entry-row .btn'); await wait(600);
  check('custom bg: unloadable image rejected, background unchanged', (await text('.row-status')).includes('could not be loaded') && (await S()).wallpaper !== 'custom');
  await os().fill('.entry', 'http://localhost:8765/dev/__audit_bg.png'); await os().press('.entry', 'Enter'); await wait(700);
  check('custom bg: Enter applies it', (await S()).wallpaper === 'custom' && (await os().$eval('#wallpaper', e => e.style.background)).includes('__audit_bg.png'));
  check('custom bg: Custom tile appears selected', await has('.wp-item.is-active[title="Custom"]'));
  await os().click(rowCtl('Remove Custom Background', 'button')); await wait();
  check('custom bg: Remove falls back to Adwaita', (await S()).wallpaper === 'adwaita' && !(await has('.wp-item[title="Custom"]')));

  console.log('— Display');
  await page('Display');
  await setRange(rowCtl('Screen Brightness', 'input'), 40); await wait();
  check('brightness 40% dims the screen', Math.abs(parseFloat(await css('#dim', 'opacity')) - (60 / 90) * 0.8) < 0.01 && (await text(rowCtl('Screen Brightness', '.range-value'))) === '40%');
  await setRange(rowCtl('Screen Brightness', 'input'), 100); await wait();
  await os().click(rowCtl('Night Light', '.switch')); await wait(800);
  check('night light on tints the screen', parseFloat(await css('#nightlight', 'opacity')) > 0.2 && await has('#tb-control .icon svg'));
  await setRange(rowCtl('Strength', 'input'), 100); await wait(800);
  check('night light strength 100% → stronger tint', Math.abs(parseFloat(await css('#nightlight', 'opacity')) - 0.5) < 0.01);
  await os().click(rowCtl('Night Light', '.switch')); await wait(800);
  check('night light off removes tint', parseFloat(await css('#nightlight', 'opacity')) === 0);
  const fs = async () => parseFloat(await os().evaluate(() => getComputedStyle(document.documentElement).fontSize));
  const base = await fs();
  await os().click('.linked-btn:has-text("Large")'); await wait();
  const large = await fs();
  await os().click('.linked-btn:has-text("Small")'); await wait();
  const small = await fs();
  await os().click('.linked-btn:has-text("Default")'); await wait();
  check(`interface size scales UI (${small.toFixed(2)} < ${base.toFixed(2)} < ${large.toFixed(2)})`, small < base && base < large && Math.abs(large / base - 1.1) < 0.01);

  console.log('— Notifications');
  await page('Notifications');
  await os().click(rowCtl('Do Not Disturb', '.switch')); await wait();
  await send({ action: 'notify', appId: 'dev.a', title: 'dnd test' }); await wait();
  check('DND suppresses banners but keeps the notification', !(await has('.banner')) && (await os().evaluate(() => document.querySelectorAll('#tb-control .icon').length)) >= 2);
  await os().click(rowCtl('Do Not Disturb', '.switch')); await wait();
  await os().click(rowCtl('Bravo', '.switch')); await wait();
  await send({ action: 'notify', appId: 'dev.b', title: 'muted test' }); await wait();
  check('per-app toggle mutes that app', !(await has('.banner')) && (await S()).mutedApps.includes('dev.b'));
  await send({ action: 'notify', appId: 'dev.a', title: 'allowed test' }); await wait();
  check('other apps still notify', await has('.banner'));
  await os().click(rowCtl('Bravo', '.switch')); await wait();

  console.log('— Lock Screen');
  await page('Lock Screen');
  await os().click(rowCtl('Notification Previews', '.switch')); await wait();
  check('previews off → lock shows only a count', await has('#lock-notifs .lock-count') && !(await has('#lock-notifs .notif')));
  await os().click(rowCtl('Notification Previews', '.switch')); await wait();
  check('previews on → lock shows notifications', await has('#lock-notifs .notif'));
  await os().click(rowCtl('Lock Screen', '.switch')); await wait();
  await send({ action: 'os:sleep' }); await wait(); await send({ action: 'os:wake' }); await wait(500);
  check('lock screen off → wake goes straight in', !(await os().$eval('#device', d => d.classList.contains('is-locked'))));
  await os().click(rowCtl('Lock Screen', '.switch')); await wait();
  await send({ action: 'os:sleep' }); await wait(); await send({ action: 'os:wake' }); await wait(500);
  check('lock screen on → wake shows lock', await os().$eval('#device', d => d.classList.contains('is-locked')));
  await send({ action: 'os:unlock' }); await wait(500);
  await os().click(rowCtl('Lock Now', 'button')); await wait();
  check('Lock Now locks', await os().$eval('#device', d => d.classList.contains('is-locked')));
  await send({ action: 'os:unlock' }); await wait(500);

  console.log('— Date & Time');
  await page('Date & Time');
  await os().click('.linked-btn:has-text("AM / PM")'); await wait();
  check('AM/PM format in top bar + preview', /[AP]M/.test(await text('#tb-clock-text')) && /[AP]M/.test(await text('.time-preview-clock')));
  await os().click('.linked-btn:has-text("24-hour")'); await wait();
  check('24-hour format', !/[AP]M/.test(await text('#tb-clock-text')));
  await os().click(rowCtl('Date in Top Bar', '.switch')); await wait();
  check('date hidden from top bar', /^\d/.test((await text('#tb-clock-text')).trim()));
  await os().click(rowCtl('Date in Top Bar', '.switch')); await wait();
  check('date shown in top bar ("Thu 24 Sep" style)', /^[A-Z][a-z]{2} \d{1,2} [A-Z][a-z]{2} /.test(await text('#tb-clock-text')));
  await os().click('.linked-btn:has-text("Sunday")'); await wait();
  await os().click('#tb-calendar'); await wait();
  const firstSun = await os().$eval('.cal-wd', e => e.textContent);
  await os().click('#tb-calendar'); await wait();
  await os().click('.linked-btn:has-text("Monday")'); await wait();
  await os().click('#tb-calendar'); await wait();
  const firstMon = await os().$eval('.cal-wd', e => e.textContent);
  await os().click('#tb-calendar'); await wait();
  check('first day of week drives the calendar', firstSun === 'S' && firstMon === 'M');

  console.log('— Apps');
  await send({ action: 'apps:launch', id: 'dev.a' }); await wait(800);
  await send({ action: 'apps:launch', id: 'system.settings' }); await wait(500);
  await page('Apps');
  await os().click(rowCtl('Alpha', '.btn:has-text("Pin to Dash")')); await wait();
  check('Pin to Dash adds to dash', await has('#dash .app-icon[data-app="dev.a"]') && (await S()).dock.includes('dev.a'));
  await os().click(rowCtl('Alpha', '.btn:has-text("Unpin")')); await wait();
  check('Unpin removes from pinned', !(await S()).dock.includes('dev.a'));
  await os().click(rowCtl('Alpha', '.btn:has-text("Force Quit")')); await wait(400);
  check('Force Quit stops the app', !(await has('.app-frame[data-app="dev.a"]')) && !(await has(rowCtl('Alpha', '.btn:has-text("Force Quit")'))));

  console.log('— System Log');
  await send({ action: 'apps:register', app: { id: 'broken' } }); await wait();
  await page('System Log');
  await os().click('.linked-btn:has-text("Errors")'); await wait();
  const levels = await os().$$eval('.journal .jl', els => [...new Set(els.map(e => e.className))]);
  check('Errors filter shows only errors', levels.length > 0 && levels.every(c => c.includes('jl-error')));
  await os().click('.linked-btn:has-text("All")'); await wait();
  await send({ action: 'notify', title: 'live tail test' }); await wait();
  check('journal tails live', (await os().$$eval('.jl-msg', els => els.map(e => e.textContent))).some(t => t.includes('live tail test')));
  await os().click('.journal-toolbar .btn:has-text("Clear")'); await wait();
  check('Clear empties the journal', (await os().$$eval('.journal .jl', els => els.length)) === 1);

  console.log('— System');
  await page('System');
  await os().click('.linked-btn:has-text("Splash")'); await wait();
  check('boot style saved', (await S()).bootStyle === 'splash');
  await os().click('.linked-btn:has-text("Boot Log")'); await wait();
  await os().click('.style-choice').catch(() => {});
  await send({ action: 'os:settings', settings: { theme: 'light', accent: '#e62d42' } }); await wait();
  await os().click(rowCtl('Reset Settings', 'button')); await wait();
  check('Reset asks for confirmation', await os().$eval('#dialog', d => d.classList.contains('is-open')));
  check('dialog does not scroll the screen', (await os().$eval('#device', d => d.scrollTop + d.scrollLeft)) === 0);
  await os().click('.dialog-btn:has-text("Cancel")'); await wait();
  check('Cancel keeps settings', (await S()).theme === 'light');
  await os().click(rowCtl('Reset Settings', 'button')); await wait();
  await os().click('.dialog-btn:has-text("Reset")'); await wait();
  check('Reset restores defaults', (await S()).theme === 'dark' && (await S()).accent === '#3584e4');

  console.log('— Control Center');
  await os().click('#tb-control'); await wait();
  await os().click('[data-toggle="dnd"] .cc-toggle-main'); await wait();
  check('CC: Do Not Disturb', (await S()).dnd === true && await has('[data-toggle="dnd"].is-active'));
  await os().click('[data-toggle="dnd"] .cc-toggle-main'); await wait();
  await os().click('[data-toggle="style"] .cc-toggle-main'); await wait();
  check('CC: Dark Style toggles theme', (await S()).theme === 'light');
  await os().click('[data-toggle="style"] .cc-toggle-main'); await wait();
  await os().click('[data-toggle="style"] .cc-toggle-arrow'); await wait();
  await os().click('.cc-accents .accent[title="green"]'); await wait();
  check('CC: accent submenu', (await S()).accent === '#3a944a' && await has('.cc-accents .accent.is-active[title="green"]'));
  await os().click('[data-toggle="night"] .cc-toggle-arrow'); await wait();
  check('CC: only one submenu open', !(await has('.cc-accents')) && await has('.cc-menu .cc-slider'));
  await setRange('.cc-menu input', 70); await wait(700);
  check('CC: night strength slider turns it on', (await S()).nightLight === true && (await S()).nightLightStrength === 70 && (await text('[data-toggle="night"] .cc-toggle-sub')) === '70%');
  await os().click('[data-toggle="night"] .cc-toggle-main'); await wait();
  check('CC: night light toggle off', (await S()).nightLight === false);
  await os().click('[data-toggle="lock"] .cc-toggle-main'); await wait();
  check('CC: lock screen toggle', (await S()).lockEnabled === false);
  await os().click('[data-toggle="lock"] .cc-toggle-main'); await wait();
  await setRange('.cc-brightness input', 55); await wait();
  check('CC: brightness', (await S()).brightness === 55);
  await setRange('.cc-brightness input', 100); await wait();
  await os().click('#tb-control'); await wait();
  await send({ action: 'apps:launch', id: 'dev.a' }); await wait(700);
  await send({ action: 'apps:launch', id: 'dev.b' }); await wait(700);
  await os().click('#tb-control'); await wait();
  const listed = await os().$$eval('.cc-app-name', els => els.map(e => e.textContent));
  check('CC: open apps listed', ['Alpha', 'Bravo', 'Settings'].every(n => listed.includes(n)));
  await os().click('.cc-app:has-text("Alpha") .cc-app-quit'); await wait(400);
  check('CC: quit one app', !(await has('.app-frame[data-app="dev.a"]')) && !(await os().$$eval('.cc-app-name', els => els.map(e => e.textContent))).includes('Alpha'));
  await os().click('.cc-app:has-text("Settings") .cc-app-main'); await wait(500);
  check('CC: clicking an app switches to it', await os().$eval('.app-frame[data-app="system.settings"]', e => e.classList.contains('is-foreground')));
  await os().click('#tb-control'); await wait();
  await os().click('.cc-section .link-btn:has-text("Quit All")'); await wait(400);
  check('CC: Quit All', (await os().$$eval('.app-frame', els => els.length)) === 0 && await has('.cc-empty'));
  await os().click('.cc-notifs'); await wait();
  check('CC: notifications link opens the message tray', (await os().$eval('#device', d => d.dataset.overlay)) === 'calendar');
  await os().click('#tb-control'); await wait();
  await os().click('.cc-round[title="Settings"]'); await wait(500);
  check('CC: Settings button', await os().$eval('.app-frame[data-app="system.settings"]', e => e.classList.contains('is-foreground')));
  await os().click('#tb-control'); await wait();
  await os().click('.cc-round[title="Lock"]'); await wait();
  check('CC: Lock button', await os().$eval('#device', d => d.classList.contains('is-locked')));

  console.log('— Persistence');
  await send({ action: 'os:unlock' }); await wait(400);
  await send({ action: 'os:settings', settings: { theme: 'light', uiScale: 'large', weekStart: 'sunday' } }); await wait();
  await p.reload(); await p.waitForTimeout(3800);
  const after = await S();
  check('settings survive a reload', after.theme === 'light' && after.uiScale === 'large' && after.weekStart === 'sunday' && (await os().evaluate(() => document.documentElement.dataset.theme)) === 'light');

  console.log(`\n${failed} failed`);
  console.log(errors.filter(e => !/needs an|Failed to load resource|404/.test(e)).join('\n') || 'no unexpected console errors');
  process.exitCode = failed ? 1 : 0;
  await b.close();
})();
